# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Catalyst-Plugin-Dojo
version:      0.01_1
version_from: lib/Catalyst/Plugin/Dojo.pm
installdirs:  site
requires:
    File::Spec:                    0
    HTML::Dojo:                    0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30
